### ISSUE TITLE
Matugen only works when launching ags from the terminal, but not from hyprland.conf

### ISSUE THREAD

**Issue by JusPLP** [Aylur/dotfiles#164]
I installed Matugen via Cargo on Arch and added 'set -gx PATH $HOME/.cargo/bin $PATH' to my Fish config. When I start ags via the terminal, Matugen works and the colors change to match my wallpaper. However, when I start it via Hyprland with 'exec-once = ags', ags works fine but Matugen doesn't. Does anyone know how I can fix this?"

**Comment by Aylur** [comment]
because your fish config is not sourced by the Hyprland session. You need to add it to PATH before launching Hyprland, your options will vary based on how you launch Hyprland, you can use a wrapper launching script, so instead of launching Hyprland, do `PATH=$PATH:$HOME/.cargo/bin Hyprland`, or some profile file that is sourced by your login manager
