### ISSUE TITLE
How to change theme to the one from screenshots?

### ISSUE THREAD

**Issue by DarkSusan** [Aylur/dotfiles#173]
Hi, I've been using ags with your dotfiles before major changes in the code and I have problem with the way the themes work, I don't get how to get the themes that existed in previous versions, I can only make light or dark with my own wallpaper and I don't know how to access your themes. I am using Endeavor Os which is arch based distro.

**Comment by keilmillerjr** [comment]
About 6 months ago, commit [23e2df4](https://github.com/Aylur/dotfiles/commit/23e2df4b06c954edee682b7cd21f2ebeb51da454) reflected important changes in the readme. Instead of pre-selected themes, you can change each option yourself in the settings panel and somewhat closely replicate the old themes. I like this approach. I have a few suggestions, that would be better suited in a new thread.
