### ISSUE TITLE
[Bug] Taskbar not respecting "Exclusive to workspaces" option

### ISSUE THREAD

**Issue by blacklightpy** [Aylur/dotfiles#190]
If I set Exclusive to workspaces, it works, until I open or close a window. At that point it acts like that setting was never enabled.

If you are instead switching workspaces, it will remove whatever was on the previous workspace from the list of visible open apps. So you have to switch through all workspaces to reset it to showing only apps from the current workspace.

**Comment by ngocminhbui** [comment]
same problem. i put a temporary fix by creating a variable;
`const counter = Variable(0)`

we update when this counter change value or workspace id change value:
```
            visible:Utils.merge([hyprland.active.workspace.bind('id'), counter.bind()], (id, b) => {
                console.log(`changed`)
                return id === client.workspace.id 
            })
 
```
finally change the counter whenever there's a deleted client:
```
.hook(hyprland, (w, address?: string) => {
            if (typeof address === "string"){
                w.children = sortItems([...w.children, AppItem(address)])
                counter.value = counter.value+1
            }
                // w.children.push(AppItem(address))

```
all these happens in Taskbar.ts

**Comment by renyuneyun** [comment]
Same issue here, on archlinux since first use (half a year ago). Current package versions (AUR packages):
- aylurs-gtk-shell 1.8.2-3
- hyprland-git 0.44.0.r73.3cec45d8-1

The trick posted by @mint44 does not seem to work for me (or maybe I didn't modify my config correctly -- instruction is not complete), unfortunately...

Anyway, even if the trick would work, the underlying issue is still there to make the original config not working in the first place, probably with ags's code as it is the one dispatches events and counting stuffs.
