### ISSUE TITLE
The Applications icon (and the App Launcher scanning icon) keeps spinning when Nix is installed

### ISSUE THREAD

**Issue by blacklightpy** [Aylur/dotfiles#212]
![image](https://github.com/Aylur/dotfiles/assets/28739146/0ae3def4-9183-4fec-a7d3-9eae388823a5)

![image](https://github.com/Aylur/dotfiles/assets/28739146/1f613d0a-c89b-44c3-aad3-f253390e8f91)

Uninstalling Nix resolves the issue.

Also when I didn't set an explicit icon, it had gone with Nix (also because my system is Void Linux, and the icon is named `void-logo`, rather than `void`; I'll make a separate issue for this: #213).

**Comment by Aylur** [comment]
it means, that `nix search nixpkgs` is still running
it runs a search ones, caches the results and uses that for the `NixRun` widget, which can be used by typing `:nx` in the applauncher

It takes a long time the first time, but if its not stopping it could mean some other unhandled error
are there any error logs?
what happens when you run `nix search nixpkgs` in a terminal?

**Comment by blacklightpy** [comment]
`error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override`

I don't know Nix well, I used it for installing an alpha release glibc dependent window manager.

**Comment by ICE-GB** [comment]
I have another situation where when using nix 2.21.1, executing the command gives an error

```
error: Must provide at least one regex! To match all packages, use 'nix search <installable> ^'.
Try 'nix --help' for more information.
```
