### ISSUE TITLE
Make new repo for ags config

### ISSUE THREAD

**Issue by Mikilio** [Aylur/dotfiles#263]
Many people here visit your dotfiles because they just want to use AGS with your config. I think it makes sense to have a repo just for that, since you have packaged it nicely.

In fact, I already created this [repo](https://github.com/Mikilio/hyprshell) I was talking about and just updated it with your recent changes as well. Since most of it is still your code, I would be happy to transfer the ownership to you.

If reviewing my changes sounds too bothersome, you can always create the repo yourself and I will make a PR, of course.

This is only a request, of course.

**Comment by Aylur** [comment]
AGS v2 is currently under heavy development https://github.com/Aylur/ags/pull/504, which will not be backwards compatible, its a rewrite from scratch.
I have already completely moved my setup to it https://github.com/Aylur/dotfiles/tree/feat/astal. It is in another private repo and I decided to not open source it this time. I've written it in a way that allows to just run selected components, so I might open source only the bar, but most of it is going to be put behind a paywall.
This is a bit of a selfish reason, but I want to profit off of it, I've been doing this off my freetime for too long now. The library, the framework and ags is still fully open source. So anyone could copy the design.

This means the ags config under this repo is no longer maintained and I no longer wish to maintain it. The bar and theming options are the same between this and next version, but everything else is drastically different. I've shared some progress on discord before.

If you wish to maintain it, you can do so, but keep in mind that it is licensed under CC 4.0, so you can modify it, redistribute it, but you always have to give credit to the original source.

**Comment by Mikilio** [comment]
I'll make sure to credit you if I keep maintaining it. Though, I might consider paying for your version if it's better.

**Comment by PlumpMath** [comment]
Here is the translated text in English:

"I am creating a paid video course on NixOS, and first of all, I want to thank you for your hard work. In fact, I struggled a lot with setting up Hyprland on NixOS for years. Then, I saw the theme you made for AGS on Reddit and was deeply impressed. Honestly, one of the reasons I became so focused on Hyprland was because I wanted to use AGS.

In my course, I'd like to share your theme and include a link to purchase it, explaining that I got permission to use it and set it up that way. Would that be possible?

I consulted with ChatGPT regarding licensing, and it said that I wouldn’t be able to include it in the course. However, I would like to ask for your permission directly. Would you be willing to allow it?"

Let me know if you need any adjustments!

Thanks!
