### ISSUE TITLE
We have to pay to have access to something you make for yourself? Dissappointed

### ISSUE THREAD

**Issue by caniko** [Aylur/dotfiles#284]
The point of FOSS is to share your stuff and make the ecosystem better. You have effectively rug-pulled us, I respect the decision. Just wanted to share my feedback.

Leaving this repository

**Comment by Aylur** [comment]
> The point of FOSS is to share your stuff

That sounds a bit like you are expecting free labor.

I've already contributed to the ecosystem by creating AGS and Astal. If you are also willing to put in effort you can create your own stuff with it. This repo does not contribute much to the ecosystem, it just adds another option for those who are looking for a pre-made setup.

> Leaving this repository

Good for you. With Astal I'm expecting a lot more similar projects, especially because its [not limited to JavaScript](https://aylur.github.io/astal/guide/getting-started/supported-languages). Hopefully you will go on to create your own thing and we will see it on [Astal showcases](https://aylur.github.io/astal/showcases/).

In the meantime you could not upgrade to agsv2, fork this repo and continue to use it.
Or look for other projects like [end4's](https://github.com/end-4/dots-hyprland) or [Jas' panel](https://hyprpanel.com/) both of which are still on v1.

**Comment by caniko** [comment]
> That sounds a bit like you are expecting free labor.

No.

**Comment by 42Willow** [comment]
I think there might have been a misunderstanding, [ags](https://github.com/Aylur/ags) and [astal](https://github.com/Aylur/astal) are still open source and still being maintained. The "ecosystem" isn't going anywhere.

It is just this repository, Aylur's personal configurations that is being made private. So if you want to do it yourself you can, for free. If you don't want to do it yourself you don't have to, you can either donate to Aylur to use their dotfiles or take *inspiration* from someone else (license permitting).

**Comment by kingmaj0r** [comment]
Couldn't you make a limited version? So basically it would not include every feature.
