### ISSUE TITLE
NixOS setup

### ISSUE THREAD

**Issue by 4Gettt25** [Aylur/dotfiles#52]
Hello, sorry if this id the wrong place to ask but I really love the Look and saw that you're using nixos with it.

The last few weeks I've been getting pretty interested in nixos so I guess my question is:

What would be the best way to incorporate these dotfiles in nixos, what would I need to change especially with home-manager and General Tips for getting this to work.

**Comment by 4Gettt25** [comment]
Okay after sittings down after work and reading the Manuals for home-manager I still can't get my head around this error. 

I've forked this repo and changes Essential things for home-manager like Username and home directory but when I try to do home-manager switch I get the following error: 
<code> the option 'wayland.windowManager.hyprland' does not exist </code>

Any Idea why this could be happening?

**Comment by Aylur** [comment]
Your home manager version is not up to date

**Comment by Janik-Haag** [comment]
> Ah ok I thought home-manager was nix exclusive my bad ^^"

that's corret home-manager is nix exclusive but nix is the package-manager and the language which can be installed and used on basically any linux and quite a few unix-like systems like darwin and freebsd. NixOS is a linux distro based on the nix package-manager and extends it with a module system which you can use to configure you system, this is what home-manager is based upon and since home-manager isn't based on nixos it works on other distros and even macos (darwin). 

> Your home manager version is not up to date

In nix you usually have channels, in this case you probably want to switch to unstable (which isn't really unstable but more like a rolling release) for both home-manager and nix. To do so you can use the `nix-channel` command. Note (on NixOS/Multiuser installs) that all the old-style nix commands (everything prefixed with `nix-`) are on user level if you execute them with your user and if you execute them with sudo/root they are system wide so for example `nix-collect-garbage --delete-old` will only delete everything not in use anymore if it is executed as root. The new style commands are all the commands you have with `nix $command` which are marked as unstable because the rfc never got merged but the implementation even so they are now actively used for over two years by a lot of people.. 

Feel free to ping me if you need any further guidance or have other questions, I'm happy to help :D
