### ISSUE TITLE
Something broken

### ISSUE THREAD

**Issue by awarewen** [Aylur/dotfiles#88]
https://github.com/Aylur/ags/assets/53365857/bccaa71e-5339-4569-b9d0-b403057c0100

- Is this a memory leak? I copied your ags configuration directly.

**Comment by Aylur** [comment]
Moved this issue to my dotfiles, because its not an issue with ags, it just sounds like you need to handle your notifications better.
I don't get a lot of notifications so I didn't bother with optimizing my notification list widget, and I still don't plan to.
You could either
- not send a notificaiton on volume changes
- fix your script so that it replaces the previous notification instead of sending a new one
- if you are already using my setup make use of the osd widget
